### ISSUE TITLE
Avoid use of __file__

### ISSUE THREAD

**Issue by jayvdb** [Kozea/tinycss2#21]
It appears the use of `__file__` here is mostly unnecessary, and can easily be  replaced with `importlib.resources`/`pkgutil.get_data`. See indygreg/PyOxidizer#69 for more info about why, but the tl;dr version is `__file__` is an optional attribute and should not be relied upon.

Currently it is only needed for loading `VERSION`, for which `importlib.resources`/`pkgutil.get_data` are ideal.

**Comment by snodo** [comment]
I also ran into trouble with this because the current implementation is not compatible with py2exe.

While it is only used to get the VERSION, I hardcoded the version string as a workaround in my installation.

**Comment by danyeaw** [comment]
Thanks for the awesome library. ❤️ 
I can confirm that https://github.com/Kozea/tinycss2/pull/27 fixes this issue that https://github.com/gaphor/gaphor has packaging with pyinstaller.

**Comment by danyeaw** [comment]
Congrats on the big update, I'm excited about the next release! :tada:
