### ISSUE TITLE
Page margin boxes background-image is ignored

### ISSUE THREAD

**Issue by LukasKlement** [Kozea/tinycss2#34]
Setting a background-image to page margin boxes used to work under version 1.0.2, however this property is now being ignored with the followed log message:
Ignored `background-image: url("path_to_example.jpg")` at 46:13, invalid value.

Example:
```
    @page {
          margin-top: 30mm;
          padding-top: 0;

          @top-center {
            content: '';
            display: block;
            width: 100%;
            height: 22.5mm;
            background-image: url('path_to_example.jpg');
            background-repeat: no-repeat;
            background-size: contain;
            background-position: 50% 50%;
            border-bottom: transparent solid 3.75mm;
          }
        }
```

Was there any reason to remove the support for page margin box background images?

**Comment by grewn0uille** [comment]
Hello!

The support for page margin box background images hasn’t been removed. That’s a change in the spec on how url is handled.

Duplicate https://github.com/Kozea/tinycss2/issues/33
