### ISSUE TITLE
Changing hex value when it starts with letter

### ISSUE THREAD

**Issue by vanjavk** [Kozea/tinycss2#37]
If you change hex value where first character is a number it will add "\3" and break parsing for most parsers.
![image](https://user-images.githubusercontent.com/1491765/104071141-cef04180-5208-11eb-8d5e-fd22be7f48f5.png)
I just used cssutils instead and had no issues anymore

**Comment by liZe** [comment]
Hello!

I don’t understand how you got the "\3" added, could you explain what you exactly did, please?

**Comment by vanjavk** [comment]
Here is reproducible code that shows it:
![image](https://user-images.githubusercontent.com/1491765/104334406-9b583480-54f2-11eb-9d7e-719a63e9a6a2.png)
![image](https://user-images.githubusercontent.com/1491765/104334429-a4e19c80-54f2-11eb-8675-3d62d761461c.png)
https://gist.github.com/vanjavk/47c70e64e1481c461a06c52096368490

**Comment by grewn0uille** [comment]
Hi!

When you change values, you have to also change the other attributes.
In this case, you have to set `is_identifier` to `False` for the Node containing `000000` and `True` to the other one.

`#000000` and `#FFFFFF` are parsed into `HashToken`. These token have a `value` and a `is_identifier` attribute.
`is_identifier` is set to `True` if the value is a valid identifier, which is the case of `FFFFFF` but not of `000000`.
When you invert the value between the two HashToken, the value of `is_identifier` is then wrong.
After, when serialize is called, it looks if the token is an identifier to know how to serialize it. As the `is_identifier` is wrong, it doesn’t use the right serialization method and it serializes `#000000` as it is a valid identifier. That’s why there is a `\3` added.

**Comment by vanjavk** [comment]
> Hi!
> 
> When you change values, you have to also change the other attributes.
> In this case, you have to set `is_identifier` to `False` for the Node containing `000000` and `True` to the other one.
> 
> `#000000` and `#FFFFFF` are parsed into `HashToken`. These token have a `value` and a `is_identifier` attribute.
> `is_identifier` is set to `True` if the value is a valid identifier, which is the case of `FFFFFF` but not of `000000`.
> When you invert the value between the two HashToken, the value of `is_identifier` is then wrong.
> After, when serialize is called, it looks if the token is an identifier to know how to serialize it. As the `is_identifier` is wrong, it doesn’t use the right serialization method and it serializes `#000000` as it is a valid identifier. That’s why there is a `\3` added.

Well thank you for an explanation, I guess I now know how to make it work, however in the meantime I completely switched to cssutils.
