### ISSUE TITLE
Parsing qualified-rules inside @media{} blocks (and other at-rules)

### ISSUE THREAD

**Issue by naggie** [Kozea/tinycss2#41]
Hi! Thanks for Tinycss2, it's made it rather easy to write a css rule-pruner for my website.

When trying to parse a stylesheet with an `@media` `at-rule`, it seems the `qualified-rule` blocks within are not actually parsed as such. They're just token streams with blocks. This makes maniplating the prelude of rules within `@media` different and quite difficult.

Is this a bug, or just a consequence of the current architecture of tinycss2?

Here's an example:

```python
import tinycss2
rules = tinycss2.parse_stylesheet('''
a {display:none;}
@media(max-width:900px) {
    b {display:none;}
}''')

```

`rules` is 

```
[<QualifiedRule … { … }>,
<WhitespaceToken>,
<AtRule @media … { … }>]
```
(Note the QualifiedRule)

`rules[3].type` is an `at-rule`, of `lower_at_keyword` `media`, with content:

```
[<WhitespaceToken>,
 <IdentToken b>,
 <WhitespaceToken>,
 <CurlyBracketsBlock { … }>,
 <WhitespaceToken>]
```
 
Note that there's no QualifiedRule.

Thanks
Callan

---

Edit:

In the mean time for anyone else with this issue, here's a workaround: when enumerating the tree, re-parse the `at-rule` content as if it were the root:

```python
rule.content = tinycss2.parse_stylesheet(tinycss2.serialize(rule.content)) 
```

This serialises back again OK.

**Comment by liZe** [comment]
Hello!

This behavior is a consequence of the [specification](https://www.w3.org/TR/css-syntax-3/#at-rule):

> This specification places no limits on what an at-rule’s block may contain. Individual at-rules must define whether they accept a block, and if so, how to parse it…

It means that tinycss2 can’t parse the rule block because it doesn’t necessarily contains rules. But:

> (preferably using one of the parser algorithms or entry points defined in this specification)

And that’s actually what you do. You can even use [`parse_rule_list`](https://doc.courtbouillon.org/tinycss2/latest/api_reference.html?highlight=parse_rule_list#tinycss2.parse_rule_list) instead of serializing the rule content.

**Comment by naggie** [comment]
Hi @liZe, thanks for the response -- that makes total sense, I ended up using: 

```
rule.content = tinycss2.parse_rule_list(rule.content)
```

Which works perfectly.

Thanks again for your help,
Cal
