### ISSUE TITLE
tests fail on Fedora as "unicode-range" != "urange"

### ISSUE THREAD

**Issue by FelixSchwarz** [Kozea/tinycss2#50]
I tried update Fedora's tinycss2 package to 1.2.0 but unfortunately the test suite fails (on F35, F36 and rawhide): [tinycss2.log](https://github.com/Kozea/tinycss2/files/9803991/tinycss2.log). It looks to me as if this is really just one error:

    AssertionError: assert [['ident', 'ù...r'], ' ', ...] == [['ident', 'ù...r'], ' ', ...]

    At index 15 diff: ['unicode-range', 18, 18] != ['urange', 18, 18]

The build runs in a container so maybe we there is a difference due to libraries or missing files?

**Comment by liZe** [comment]
Hi!

It looks like you use the `color4` branch of the `css-parsing-tests`, as it includes [this commit](https://github.com/CourtBouillon/css-parsing-tests/commit/825627b5057b3b672bb9935fd4aa98cab30cfc1f). You should use the [current master branch @c5749e5](https://github.com/SimonSapin/css-parsing-tests/tree/c5749e51dda3868b3e8062e65a36584c2fec8059) instead.

**Comment by FelixSchwarz** [comment]
Just so I understand: `urange` is unexpected/outdated and the code/tests should only use `unicode-range`?

Actually I'm just using the pypi tarball and we just have a tiny patch for `pyproject.toml`. Can you check the contents of the pypi tarball? Maybe something went wrong when creating the tarball?

**Comment by liZe** [comment]
My bad, I’ll release a new version today. Thanks for your report.

**Comment by FelixSchwarz** [comment]
Thank you for the quick fix (and your work in general!).
