### ISSUE TITLE
Missing type annotations

### ISSUE THREAD

**Issue by PatrCo** [Kozea/tinycss2#60]
tinycss2 currently doesn’t support type checking. I wrote some stubs, which may or may not be of use for others, but don’t know whether to share them nor where to share them.
So, in case of interest:
[stubs_for_tinycss2_and_webencodings.zip](https://github.com/user-attachments/files/16624434/stubs_for_tinycss2_and_webencodings.zip)

**Comment by liZe** [comment]
Hi!

Thanks for sharing.

As explained in Kozea/Pyphen#50, we’re currently not interested in type annotations. If you’re interested, you can propose them to [typeshed](https://github.com/python/typeshed).
