### ISSUE TITLE
parse css to ast tree

### ISSUE THREAD

**Issue by djn3m0** [Kozea/tinycss2#7]
Hello,

I want to parse a given CSS code and get ast tree of that code and finally convert that ast tree back to code!
I found some AST related functionality but I cannot find any example code to use them. Can you please give me some example of the AST functionalities?

Thank you

**Comment by liZe** [comment]
I'm a bit late, but… Are you looking for `serialize`?

```python
import tinycss2
nodes = tinycss2.parse_stylesheet("div { background: red }")
print(tinycss2.serialize(nodes))
```

**Comment by liZe** [comment]
@djn3m0 Feel free to reopen if you need anything.
