### ISSUE TITLE
CSS variables support

### ISSUE THREAD

**Issue by stevenle** [Kozea/tinycss2#8]
Looks like the serialized output of CSS vars inserts `/**/` for some reason. I'm basically doing `tinycss2.serialize(tinycss2.parse(css))` and  I'm getting the following:

input:

```
:root {
  --header-height: 300px;
}

.foo {
  height: calc(100vh - var(--header-height) - 64px);
}
```

output:

```
:root {
  -/**/-header-height: 300px;
}

.foo {
  height: calc(100vh - var(-/**/-header-height) - 64px);
}
```

Mozilla docs about CSS vars: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables

**Comment by liZe** [comment]
The tokenizer has been updated to allow two dashes at the beginning of ident tokens (as per [draft](https://drafts.csswg.org/css-syntax/#ident-token-diagram)).
